[package]
name = "dmoj"
description = "A Rust crate for providing helpful methods in online judging"
version = "0.1.0"
authors = ["Martin Muñoz <im.mmun@gmail.com>"]
license = "AGPL-3.0"

[dependencies]
lazy_static = "0.2.1"
